name: pulseai
description: "PulseAI - AI-powered health monitoring app"
publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  camera: ^0.10.5
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.3.2
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0
  translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/google.png
    - assets/images/logo.png
    - assets/images/
    - assets/data/hospitals.geojson

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
